# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highscore',
            field=models.IntegerField(default=0),
        ),
    ]
